stop_string_criteria:
  _target_: transformers.generation.StopStringCriteria
  tokenizer: ${tokenizer}
  stop_strings:
    # Select tokens from https://github.com/EleutherAI/lm-evaluation-harness/blob/main/lm_eval/tasks/gsm8k/gsm8k-cot-llama.yaml#L59-L64
    - '<|eot_id|>'
    - '<|start_header_id|>user<|end_header_id|>'
    - '<|im_end|>'
