defaults:
  - generation_config@_here_
  - _self_
_target_: src.denoiser.diffusion.DiffusionGenerationConfig
num_steps: 1000
min_t: 1e-5
block_size: ${block_size}
first_hitting: true
confidence_based_noising: true
confidence_threshold: 1.0
align_inputs_to_blocks: false
