# Sets defaults for composer scripts
defaults:
  - trainer: trainer
  - algorithms:
    - ema
    - gradient_clipping
    - set_fixed_rng_state_for_eval
  - callbacks:
      - runtime_estimator
      - lr_monitor
      - speed_monitor
      - log_gradient_norms
      - hf_compatible_checkpointing
      - save_best_checkpointing
  - loggers: wandb
  - lr_scheduler: constant_with_warmup
  - optimizer: decoupled_adamw
