defaults:
  - default_composer  # Pull in composer setup defaults
  - overrides algorithms:
    - ema
    - gradient_clipping
    - set_fixed_rng_state_for_eval
    - block_size_annealing
  - overrides callbacks:
    - runtime_estimator
    - lr_monitor
    - speed_monitor
    - log_gradient_norms
    - log_block_size
    - hf_compatible_checkpointing
    - save_best_checkpointing
  - _self_
