hf_compatible_checkpointing:
  _target_: src.custom_composer.callbacks.HuggingFaceCompatibleCheckpointing
  folder: ${checkpointing.save_dir}
  filename: 'ep{epoch}-ba{batch}-rank{rank}.pt'
  latest_filename: 'latest-rank{rank}.pt'
  save_interval: '100000ba'
  num_checkpoints_to_keep: -1
  overwrite: false
  disable_hf: false
  save_local: true
  save_to_hub: true
  hub_repo_id: kuleshov-group/${run_name}
