save_best_checkpointing:
  _target_: src.custom_composer.callbacks.SaveBestCheckpointing
  folder: ${checkpointing.save_dir}
  filename: 'best-rank{rank}.pt'
  num_checkpoints_to_keep: -1
  metric_to_monitor: eval/nll  # <train|val>/<metric_name>
  mode: 'min'
  disable_hf: true
  save_local: false
  save_to_hub: false
  hub_repo_id: null
